import io
from datetime import datetime, timezone
from xml.sax.saxutils import escape as _xml_escape, quoteattr as _xml_quoteattr

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem,
)

from docx import Document
from docx.shared import Pt, RGBColor

from backend.models.schemas import InteractionResult

RISK_HEX = {"high": "#991b1b", "moderate": "#92400e", "low": "#065f46", "unknown": "#475569"}
RISK_RGB = {
    "high": RGBColor(0x99, 0x1B, 0x1B), "moderate": RGBColor(0x92, 0x40, 0x0E),
    "low": RGBColor(0x06, 0x5F, 0x46), "unknown": RGBColor(0x47, 0x55, 0x69),
}


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _esc(text: str) -> str:
    """Escape text for ReportLab's mini-XML markup — every dynamic string
    (drug names, URLs, LLM-authored text) must go through this before being
    interpolated into a Paragraph. A source URL containing a literal quote
    character (seen in practice: openfda.generic_name:"warfarin") broke the
    attribute parser before this was added — not a hypothetical edge case."""
    return _xml_escape(text)


def _esc_attr(text: str) -> str:
    """Escape + quote an attribute value (e.g. an href) for ReportLab markup."""
    return _xml_quoteattr(text)


def build_pdf(result: InteractionResult) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=18, spaceAfter=4)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceBefore=14, spaceAfter=6)
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=15)
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#64748b"))
    risk_style = ParagraphStyle(
        "Risk", parent=styles["Normal"], fontSize=12,
        textColor=colors.HexColor(RISK_HEX.get(result.risk_level.value, "#475569")), spaceAfter=10,
    )

    story = [
        Paragraph("Drug-Drug Interaction Report", h1),
        Paragraph(f"{_esc(result.drug_a.standard_name)} + {_esc(result.drug_b.standard_name)}", body),
        Paragraph(f"Risk level: {_esc(result.risk_level.value.upper())}", risk_style),
        Paragraph("Summary", h2),
        Paragraph(_esc(result.llm_summary), body),
        Paragraph("Mechanism — Verified (ChEMBL)", h2),
    ]

    for drug in (result.drug_a, result.drug_b):
        if drug.verified_mechanisms:
            for m in drug.verified_mechanisms:
                refs = ", ".join(
                    f'<a href={_esc_attr(r.ref_url)} color="blue">{_esc(r.ref_type)}</a>' for r in m.references
                ) or "no references"
                action = f" ({_esc(m.action_type)})" if m.action_type else ""
                story.append(Paragraph(
                    f"<b>{_esc(drug.standard_name)}</b> — target: {_esc(m.target)}{action}"
                    f"<br/>{_esc(m.mechanism_of_action)}<br/>References: {refs}",
                    body,
                ))
        else:
            story.append(Paragraph(
                f"<b>{_esc(drug.standard_name)}</b> — no independently verified mechanism found in ChEMBL.", body
            ))
        story.append(Spacer(1, 6))

    story.append(Paragraph("Mechanism — AI-synthesized (not independently verified)", h2))
    story.append(Paragraph(_esc(result.mechanism), body))
    targets = ", ".join(result.targets_involved) or "none"
    story.append(Paragraph(
        f"Type: {_esc(result.mechanism_type.value)} · Targets mentioned: {_esc(targets)}", body
    ))
    if result.pathway:
        story.append(Paragraph(_esc(result.pathway).replace("\n", "<br/>"), body))

    story.append(Paragraph("Clinical Effect", h2))
    story.append(Paragraph(_esc(result.clinical_effect), body))
    story.append(Paragraph("Recommendation", h2))
    story.append(Paragraph(_esc(result.recommendation), body))

    story.append(Paragraph("Sources", h2))
    if result.sources:
        items = [
            ListItem(Paragraph(f'{_esc(s.name)} — <a href={_esc_attr(s.url)} color="blue">{_esc(s.url)}</a>', body))
            for s in result.sources
        ]
        story.append(ListFlowable(items, bulletType="bullet"))
    else:
        story.append(Paragraph(
            "No independently-cited sources — relied on the LLM's own pharmacology knowledge.", body
        ))

    story.append(Spacer(1, 14))
    story.append(Paragraph(_esc(result.disclaimer), small))
    story.append(Paragraph(f"Generated by DDI Checker on {_timestamp()} — for research purposes only.", small))

    doc.build(story)
    return buf.getvalue()


def build_docx(result: InteractionResult) -> bytes:
    doc = Document()

    doc.add_heading("Drug-Drug Interaction Report", level=1)
    doc.add_paragraph(f"{result.drug_a.standard_name} + {result.drug_b.standard_name}")

    risk_p = doc.add_paragraph()
    risk_run = risk_p.add_run(f"Risk level: {result.risk_level.value.upper()}")
    risk_run.bold = True
    risk_run.font.color.rgb = RISK_RGB.get(result.risk_level.value, RGBColor(0x47, 0x55, 0x69))

    doc.add_heading("Summary", level=2)
    doc.add_paragraph(result.llm_summary)

    doc.add_heading("Mechanism — Verified (ChEMBL)", level=2)
    for drug in (result.drug_a, result.drug_b):
        doc.add_paragraph().add_run(drug.standard_name).bold = True
        if drug.verified_mechanisms:
            for m in drug.verified_mechanisms:
                label = f"Target: {m.target}" + (f" ({m.action_type})" if m.action_type else "")
                doc.add_paragraph(label, style="List Bullet")
                doc.add_paragraph(m.mechanism_of_action, style="List Bullet")
                for r in m.references:
                    doc.add_paragraph(f"{r.ref_type}: {r.ref_url}", style="List Bullet")
        else:
            doc.add_paragraph("No independently verified mechanism found in ChEMBL.", style="List Bullet")

    doc.add_heading("Mechanism — AI-synthesized (not independently verified)", level=2)
    doc.add_paragraph(result.mechanism)
    doc.add_paragraph(
        f"Type: {result.mechanism_type.value} · Targets mentioned: {', '.join(result.targets_involved) or 'none'}"
    )
    if result.pathway:
        doc.add_paragraph(result.pathway)

    doc.add_heading("Clinical Effect", level=2)
    doc.add_paragraph(result.clinical_effect)
    doc.add_heading("Recommendation", level=2)
    doc.add_paragraph(result.recommendation)

    doc.add_heading("Sources", level=2)
    if result.sources:
        for s in result.sources:
            doc.add_paragraph(f"{s.name} — {s.url}", style="List Bullet")
    else:
        doc.add_paragraph("No independently-cited sources — relied on the LLM's own pharmacology knowledge.")

    doc.add_paragraph()
    disclaimer_run = doc.add_paragraph().add_run(result.disclaimer)
    disclaimer_run.italic = True
    disclaimer_run.font.size = Pt(9)

    footer_run = doc.add_paragraph().add_run(
        f"Generated by DDI Checker on {_timestamp()} — for research purposes only."
    )
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(0x64, 0x74, 0x8B)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
